name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Init TWA
        run: |
          bubblewrap init --manifest https://iamvinay-dev.github.io/student-tracker/manifest.json --skipPwaValidation

      - name: Build APK
        run: bubblewrap build
